"use client";
import "@styles/globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { AuthProvider } from "@providers";
import { ChakraProvider } from "@chakra-ui/react";
import { Header } from "@components";

// const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ChakraProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
